version: '2.4'

services:
  server:
    image: eclipse-temurin:17-jre-alpine
    command: ["java", "-jar", "threeServerOnJava.jar", "-n", "catalog.json"]
    ports:
      - "0.0.0.0:8080:8080"
#    restart: always
    volumes:
      - ./catalog:/app/
    working_dir: /app

# docker network create app
networks:
  default:
    external:
      name: "app"
